apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
- name: grafana
  version: 6.x
  repository: https://grafana.github.io/helm-charts

